// @ts-check
import eslint from "@eslint/js";
import { defineConfig } from "eslint/config";
import tseslint from "typescript-eslint";
import angular from "angular-eslint";
import storybook from "eslint-plugin-storybook";

export default defineConfig([
  {
    // Generated by openapi-typescript (S8, openapi:check); reformatting or
    // hand-fixing lint findings here would just be undone by the next
    // `npm run openapi:generate` run.
    ignores: ["src/app/core/http/api-types.gen.ts"],
  },
  {
    files: ["**/*.ts"],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      // CLAUDE.md: "Strict TypeScript, no `any` outside audited adapters."
      "@typescript-eslint/no-explicit-any": "error",
      "@angular-eslint/directive-selector": [
        "error",
        {
          type: "attribute",
          prefix: "app",
          style: "camelCase",
        },
      ],
      "@angular-eslint/component-selector": [
        "error",
        {
          type: "element",
          prefix: "app",
          style: "kebab-case",
        },
      ],
    },
  },
  {
    files: ["**/*.html"],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {},
  },
  {
    files: ["**/*.stories.ts"],
    extends: [storybook.configs["flat/recommended"]],
  },
]);
