/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public frontend bootstrap configuration, fetched before shell render */
        get: operations["BootstrapController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start the OIDC login redirect (top-level browser navigation, not an XHR call) */
        get: operations["AuthController_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC authorization-code callback; sets the BFF session cookies and redirects */
        get: operations["AuthController_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identify the current session, if any */
        get: operations["AuthController_whoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current Dentix session */
        post: operations["AuthController_logoutHandler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search patients by name or phone, or list most recent when query is empty */
        get: operations["PatientsController_list"];
        put?: never;
        /** Create a patient */
        post: operations["PatientsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MoneyBootstrapConfigDto: {
            /** @enum {string} */
            defaultUnit: "RIAL" | "TOMAN";
            /** @description Always true in v1 — the unit label can never be configured away. */
            showUnitLabel: boolean;
        };
        BootstrapConfigResponseDto: {
            /** @enum {string} */
            locale: "fa-IR";
            /** @enum {string} */
            dir: "rtl";
            /** @enum {string} */
            calendarDisplay: "JALALI";
            /** @description IANA timezone identifier. */
            timezone: string;
            money: components["schemas"]["MoneyBootstrapConfigDto"];
            /** @description Same-origin API path prefix; relative, never an absolute host. */
            apiBaseUrl: string;
            appVersion: string;
        };
        ErrorResponseDto: {
            /** @description Stable, locale-neutral error code (05-api-guidelines.md). */
            code: string;
        };
        WhoAmIResponseDto: {
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            officeId: string;
            displayName: string;
            /** @description Bumped when the user's permissions change, so a stale client can detect it. */
            permissionVersion: number;
            /**
             * Format: date-time
             * @description RFC 3339 instant of the current session's authentication.
             */
            authenticatedAt: string;
            /** @description Whether authentication happened recently enough for sensitive actions. */
            isRecentlyAuthenticated: boolean;
        };
        LogoutResponseDto: {
            /**
             * Format: uri
             * @description Provider end-session URL the browser should follow to also end the Keycloak SSO session.
             */
            providerEndSessionUrl: string;
        };
        CreatePatientRequestDto: {
            /** @description Patient's name as entered, typically Persian. */
            nativeName: string;
            /** @description Optional Latin-script name, stored and displayed unmirrored in RTL. */
            latinName?: string | null;
            /** @description Iranian mobile number in any common display form (09…, +98…, Persian digits). */
            phone?: string | null;
            /** @description True only when the patient explicitly has no contact method. */
            contactUnavailable?: boolean;
            /** @enum {string} */
            sex?: "male" | "female" | "unspecified";
            /**
             * Format: date
             * @description Canonical Gregorian ISO date (YYYY-MM-DD) — converted from the Jalali picker at the UI boundary (ADR-008/012).
             */
            dateOfBirth?: string | null;
        };
        CreatePatientResponseDto: {
            /** Format: uuid */
            id: string;
            /** @description Office-scoped sequential patient number. */
            patientNumber: number;
        };
        PatientSearchResultDto: {
            /** Format: uuid */
            id: string;
            patientNumber: number;
            nativeName: string;
            latinName: string | null;
            phone: string | null;
            /**
             * Format: date
             * @description Canonical Gregorian ISO date (YYYY-MM-DD), or null where not recorded.
             */
            dateOfBirth: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    BootstrapController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapConfigResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the OIDC provider's authorization endpoint. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed returnTo path. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect back into the app, authenticated (or to /login?error=... on failure). */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_whoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmIResponseDto"];
                };
            };
            /** @description No session, or an invalid/expired one. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_logoutHandler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    PatientsController_list: {
        parameters: {
            query?: {
                /** @description Name or phone fragment; omit to list most recent. */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientSearchResultDto"][];
                };
            };
        };
    };
    PatientsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePatientRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePatientResponseDto"];
                };
            };
            /** @description Validation failure, e.g. NATIVE_NAME_REQUIRED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
