/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public frontend bootstrap configuration, fetched before shell render */
        get: operations["BootstrapController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start the OIDC login redirect (top-level browser navigation, not an XHR call)
         * @description Pass `prompt=login` to force interactive re-authentication — used to recover from RECENT_AUTHENTICATION_REQUIRED, since only a fresh interactive login advances `auth_time`.
         */
        get: operations["AuthController_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC authorization-code callback; sets the BFF session cookies and redirects */
        get: operations["AuthController_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identify the current session, if any */
        get: operations["AuthController_whoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current Dentix session */
        post: operations["AuthController_logoutHandler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/office-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link an existing identity-provider account to this office */
        post: operations["OfficeUsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a patient */
        post: operations["PatientsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search patients by name, phone, or patient number, or list most recent when query is empty */
        post: operations["PatientsController_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single patient's full record */
        get: operations["PatientsController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct a patient's demographics (never their status — see the transition endpoints) */
        patch: operations["PatientsController_updateDemographics"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MoneyBootstrapConfigDto: {
            /** @enum {string} */
            defaultUnit: "RIAL" | "TOMAN";
            /** @description Always true in v1 — the unit label can never be configured away. */
            showUnitLabel: boolean;
        };
        BootstrapConfigResponseDto: {
            /** @enum {string} */
            locale: "fa-IR";
            /** @enum {string} */
            dir: "rtl";
            /** @enum {string} */
            calendarDisplay: "JALALI";
            /** @description IANA timezone identifier. */
            timezone: string;
            money: components["schemas"]["MoneyBootstrapConfigDto"];
            /** @description Same-origin API path prefix; relative, never an absolute host. */
            apiBaseUrl: string;
            appVersion: string;
        };
        ErrorResponseDto: {
            /** @description Stable, locale-neutral error code (05-api-guidelines.md). */
            code: string;
        };
        WhoAmIResponseDto: {
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            officeId: string;
            displayName: string;
            /** @description Bumped when the user's permissions change, so a stale client can detect it. */
            permissionVersion: number;
            /**
             * Format: date-time
             * @description RFC 3339 instant of the current session's authentication.
             */
            authenticatedAt: string;
            /** @description Whether authentication happened recently enough for sensitive actions. */
            isRecentlyAuthenticated: boolean;
            /** @description UI convenience only, not an authorization decision — whether to offer the add-user entry point. The server re-checks independently on the actual request. */
            canManageUsers: boolean;
        };
        LogoutResponseDto: {
            /**
             * Format: uri
             * @description Provider end-session URL the browser should follow to also end the Keycloak SSO session.
             */
            providerEndSessionUrl: string;
        };
        AddOfficeUserRequestDto: {
            /** @description Must match an existing, enabled account in the identity provider. */
            email: string;
            /**
             * @description One of the six fixed roles. Custom roles are not supported.
             * @enum {string}
             */
            roleCode: "dentist" | "dental_assistant" | "receptionist" | "cashier" | "office_manager" | "system_administrator";
        };
        AddOfficeUserResponseDto: {
            /** Format: uuid */
            officeUserId: string;
        };
        CreatePatientRequestDto: {
            /** @description Patient's name as entered, typically Persian. */
            nativeName: string;
            /** @description Optional Latin-script name, stored and displayed unmirrored in RTL. */
            latinName?: string | null;
            /** @description Iranian mobile number in any common display form (09…, +98…, Persian digits). */
            phone?: string | null;
            /** @description True only when the patient explicitly has no contact method. */
            contactUnavailable?: boolean;
            /** @enum {string} */
            sex?: "male" | "female" | "unspecified";
            /**
             * Format: date
             * @description Canonical Gregorian ISO date (YYYY-MM-DD) — converted from the Jalali picker at the UI boundary (ADR-008/012).
             */
            dateOfBirth?: string | null;
            /**
             * @description Determines whether identifierNumber is validated as a national code or a passport number.
             * @default iranian
             * @enum {string}
             */
            nationality: "iranian" | "foreign";
            /** @description National code (کد ملی) for an iranian patient, or a passport number for a foreign one — see `nationality`. Only when legally and operationally justified. Optional; never blocks registration when omitted. */
            identifierNumber?: string | null;
            /** @description Optional email address, validated when provided. */
            email?: string | null;
            /** @description Address: province. */
            province?: string | null;
            /** @description Address: city. */
            city?: string | null;
            /** @description Address: district/locality. */
            district?: string | null;
            /** @description Address: street/address line 1. */
            addressLine1?: string | null;
            /** @description Address: street/address line 2. */
            addressLine2?: string | null;
            /** @description Address: postal code. */
            postalCode?: string | null;
            /** @description Address: free-form delivery notes. */
            deliveryNotes?: string | null;
            /** @description Patient's occupation, free text. */
            occupation?: string | null;
            /** @description How the patient found the office, free text. */
            referralSource?: string | null;
        };
        CreatePatientResponseDto: {
            /** Format: uuid */
            id: string;
            /** @description Office-scoped sequential patient number. */
            patientNumber: number;
        };
        SearchPatientsRequestDto: {
            /** @description Name, mobile number, or patient number fragment; omit to list most recent. */
            query?: string;
            /** @default 25 */
            limit: number;
        };
        PatientSearchResultDto: {
            /** Format: uuid */
            id: string;
            patientNumber: number;
            nativeName: string;
            latinName: string | null;
            phone: string | null;
            /**
             * Format: date
             * @description Canonical Gregorian ISO date (YYYY-MM-DD), or null where not recorded.
             */
            dateOfBirth: string | null;
        };
        PatientDetailResponseDto: {
            /** Format: uuid */
            id: string;
            /** @description Office-scoped sequential patient number. */
            patientNumber: number;
            /** @enum {string} */
            status: "active" | "inactive" | "deceased" | "duplicate_candidate" | "archived";
            nativeName: string;
            latinName: string | null;
            phone: string | null;
            contactUnavailable: boolean;
            email: string | null;
            /**
             * Format: date
             * @description Canonical Gregorian ISO date (YYYY-MM-DD), or null where not recorded.
             */
            dateOfBirth: string | null;
            /** @enum {string} */
            sex: "male" | "female" | "unspecified";
            /** @enum {string} */
            nationality: "iranian" | "foreign";
            /** @description National code for an iranian patient, passport number for a foreign one — see nationality. */
            identifierNumber: string | null;
            province: string | null;
            city: string | null;
            district: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            postalCode: string | null;
            deliveryNotes: string | null;
            occupation: string | null;
            referralSource: string | null;
            /**
             * @description No edit control exists for this yet — there is exactly one valid value today.
             * @enum {string}
             */
            preferredLanguage: "fa-IR";
            /** @description Optimistic-concurrency version — also echoed as the response's ETag header. */
            version: number;
        };
        UpdatePatientDemographicsRequestDto: {
            /** @description Patient's name as entered, typically Persian. */
            nativeName: string;
            /** @description Optional Latin-script name, stored and displayed unmirrored in RTL. */
            latinName?: string | null;
            /** @description Iranian mobile number in any common display form (09…, +98…, Persian digits). */
            phone?: string | null;
            /** @description True only when the patient explicitly has no contact method. */
            contactUnavailable?: boolean;
            /** @enum {string} */
            sex?: "male" | "female" | "unspecified";
            /**
             * Format: date
             * @description Canonical Gregorian ISO date (YYYY-MM-DD) — converted from the Jalali picker at the UI boundary.
             */
            dateOfBirth?: string | null;
            /**
             * @description Determines whether identifierNumber is validated as a national code or a passport number.
             * @default iranian
             * @enum {string}
             */
            nationality: "iranian" | "foreign";
            /** @description National code (کد ملی) for an iranian patient, or a passport number for a foreign one. */
            identifierNumber?: string | null;
            /** @description Optional email address, validated when provided. */
            email?: string | null;
            /** @description Address: province. */
            province?: string | null;
            /** @description Address: city. */
            city?: string | null;
            /** @description Address: district/locality. */
            district?: string | null;
            /** @description Address: street/address line 1. */
            addressLine1?: string | null;
            /** @description Address: street/address line 2. */
            addressLine2?: string | null;
            /** @description Address: postal code. */
            postalCode?: string | null;
            /** @description Address: free-form delivery notes. */
            deliveryNotes?: string | null;
            /** @description Patient's occupation, free text. */
            occupation?: string | null;
            /** @description How the patient found the office, free text. */
            referralSource?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    BootstrapController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapConfigResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the OIDC provider's authorization endpoint. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed returnTo path. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect back into the app, authenticated (or to /login?error=... on failure). */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_whoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmIResponseDto"];
                };
            };
            /** @description No session, or an invalid/expired one. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_logoutHandler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    OfficeUsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddOfficeUserRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddOfficeUserResponseDto"];
                };
            };
            /** @description e.g. NOT_FOUND_IN_PROVIDER, ALREADY_LINKED, PROVIDER_ACCOUNT_DISABLED, ROLE_NOT_FOUND */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description FORBIDDEN (actor is not an office admin) or RECENT_AUTHENTICATION_REQUIRED (session authenticated too long ago for permission administration). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    PatientsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePatientRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePatientResponseDto"];
                };
            };
            /** @description Validation failure, e.g. NATIVE_NAME_REQUIRED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description MISSING_PERMISSION — the caller's roles do not grant patient.create. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    PatientsController_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchPatientsRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientSearchResultDto"][];
                };
            };
            /** @description MISSING_PERMISSION — the caller's roles do not grant patient.view. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    PatientsController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDetailResponseDto"];
                };
            };
            /** @description MISSING_PERMISSION — the caller's roles do not grant patient.view. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description PATIENT_NOT_FOUND — unknown ID, or the patient belongs to another office. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    PatientsController_updateDemographics: {
        parameters: {
            query?: never;
            header: {
                /** @description The `version` last read from GET /patients/:id's ETag. */
                "If-Match": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePatientDemographicsRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDetailResponseDto"];
                };
            };
            /** @description Validation failure, e.g. INVALID_PHONE */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description MISSING_PERMISSION — the caller's roles do not grant patient.edit-demographics. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description PATIENT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description MISSING_IF_MATCH or VERSION_CONFLICT — the caller's copy is missing or stale; re-fetch and retry. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
