/**
 * Branded string types so a PatientId can't be passed where an OfficeId is
 * expected, even though both are plain UUID strings at runtime.
 * Per 04-architecture/04-data-model.md: "Business identifiers are UUIDs
 * generated by the application or PostgreSQL."
 */
declare const brand: unique symbol;
export type Branded<TValue, TBrand extends string> = TValue & { readonly [brand]: TBrand };

export type Uuid = Branded<string, "Uuid">;

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function isUuid(value: string): value is Uuid {
  return UUID_PATTERN.test(value);
}

export function asUuid(value: string): Uuid {
  if (!isUuid(value)) {
    throw new Error(`Not a valid UUID: ${value}`);
  }
  return value;
}
