import {
  formatJalali,
  gregorianToJalali,
  isJalaliLeapYear,
  isoDateToJalali,
  isValidJalaliDate,
  jalaliMonthLength,
  jalaliToGregorian,
  jalaliToIsoDate,
  parseJalaliInput,
  toPersianDigits,
} from "./jalali";

/**
 * ADR-008's blocking fixture suite. Every fixture below was generated by
 * `jalaali-js` and independently cross-checked against the platform's own
 * ICU implementation (`Intl.DateTimeFormat` with `calendar: 'persian'`,
 * queried directly in Node — see the ADR's implementation note for the
 * exact commands) before being frozen here — not hand-typed guesses.
 * jalaali-js's own docs note its Borkowski-algorithm result diverges from
 * ICU's rule outside Gregorian [1800, 2256]; every fixture here falls
 * well inside that range, so agreement is expected and meaningful.
 */
describe("Jalali fixture suite (ADR-008)", () => {
  describe("Nowruz boundary — leap year 1403", () => {
    it("2024-03-20 is Farvardin 1, 1403 (Nowruz)", () => {
      expect(gregorianToJalali({ year: 2024, month: 3, day: 20 })).toEqual({
        year: 1403,
        month: 1,
        day: 1,
      });
    });

    it("1403 is a leap year, so its Esfand has 30 days, landing on 2025-03-20", () => {
      expect(isJalaliLeapYear(1403)).toBe(true);
      expect(jalaliMonthLength(1403, 12)).toBe(30);
      expect(gregorianToJalali({ year: 2025, month: 3, day: 20 })).toEqual({
        year: 1403,
        month: 12,
        day: 30,
      });
      expect(isValidJalaliDate({ year: 1403, month: 12, day: 30 })).toBe(true);
    });
  });

  describe("Nowruz boundary — non-leap year 1404", () => {
    it("2025-03-21 is Farvardin 1, 1404 (Nowruz)", () => {
      expect(gregorianToJalali({ year: 2025, month: 3, day: 21 })).toEqual({
        year: 1404,
        month: 1,
        day: 1,
      });
    });

    it("1404 is not a leap year, so its Esfand has only 29 days, landing on 2026-03-20", () => {
      expect(isJalaliLeapYear(1404)).toBe(false);
      expect(jalaliMonthLength(1404, 12)).toBe(29);
      expect(gregorianToJalali({ year: 2026, month: 3, day: 20 })).toEqual({
        year: 1404,
        month: 12,
        day: 29,
      });
    });

    it("rejects Esfand 30 in the non-leap year 1404", () => {
      expect(isValidJalaliDate({ year: 1404, month: 12, day: 30 })).toBe(false);
    });
  });

  describe("Gregorian year boundary inside the Jalali month of Dey", () => {
    it("Dey 1, 1404 falls on 2025-12-22 (Gregorian)", () => {
      expect(gregorianToJalali({ year: 2025, month: 12, day: 22 })).toEqual({
        year: 1404,
        month: 10,
        day: 1,
      });
    });

    it("Dey 20, 1404 falls on 2026-01-10 — the Gregorian year rolled over mid-month, the Jalali month did not", () => {
      expect(gregorianToJalali({ year: 2026, month: 1, day: 10 })).toEqual({
        year: 1404,
        month: 10,
        day: 20,
      });
    });
  });

  describe("Round-trip law", () => {
    const fixtures = [
      { year: 1369, month: 2, day: 25 }, // 1990-05-15
      { year: 1357, month: 11, day: 22 }, // 1979-02-11
      { year: 1403, month: 12, day: 30 }, // Esfand 30 of a leap year
      { year: 1404, month: 1, day: 1 }, // Nowruz of a non-leap year
    ];

    it.each(fixtures)("Jalali -> Gregorian -> Jalali is the identity for %o", (jalali) => {
      expect(gregorianToJalali(jalaliToGregorian(jalali))).toEqual(jalali);
    });

    it.each([
      { year: 1990, month: 5, day: 15 },
      { year: 1979, month: 2, day: 11 },
      { year: 2025, month: 3, day: 20 },
      { year: 2025, month: 3, day: 21 },
    ])("Gregorian -> Jalali -> Gregorian is the identity for %o", (gregorian) => {
      expect(jalaliToGregorian(gregorianToJalali(gregorian))).toEqual(gregorian);
    });
  });

  describe("ISO date string <-> Jalali", () => {
    it("converts a canonical ISO date to Jalali", () => {
      expect(isoDateToJalali("1990-05-15")).toEqual({ year: 1369, month: 2, day: 25 });
    });

    it("converts Jalali back to a zero-padded canonical ISO date", () => {
      expect(jalaliToIsoDate({ year: 1369, month: 2, day: 25 })).toBe("1990-05-15");
    });

    it("rejects a non-ISO string rather than guessing", () => {
      expect(() => isoDateToJalali("15/05/1990")).toThrow(/not an ISO date/);
    });
  });

  describe("formatJalali", () => {
    it("zero-pads month and day", () => {
      expect(formatJalali({ year: 1369, month: 2, day: 5 })).toBe("1369/02/05");
    });
  });

  describe("toPersianDigits", () => {
    it("converts a Latin-digit string to Persian digits", () => {
      expect(toPersianDigits("1369/02/25")).toBe("۱۳۶۹/۰۲/۲۵");
    });
  });

  describe("parseJalaliInput — Persian and Latin digits parse to the same canonical value", () => {
    it("parses Latin digits with a slash separator", () => {
      expect(parseJalaliInput("1369/02/25")).toEqual({ year: 1369, month: 2, day: 25 });
    });

    it("parses Persian digits with a slash separator to the identical value", () => {
      expect(parseJalaliInput("۱۳۶۹/۰۲/۲۵")).toEqual({ year: 1369, month: 2, day: 25 });
    });

    it("parses a dash separator and mixed Persian/Latin digits", () => {
      expect(parseJalaliInput("۱۳۶۹-02-۲۵")).toEqual({ year: 1369, month: 2, day: 25 });
    });

    it("tolerates surrounding whitespace", () => {
      expect(parseJalaliInput("  1369/02/25  ")).toEqual({ year: 1369, month: 2, day: 25 });
    });

    it("rejects Esfand 30 of a non-leap year rather than accepting an invalid date", () => {
      expect(parseJalaliInput("1404/12/30")).toBeNull();
    });

    it("rejects garbage input", () => {
      expect(parseJalaliInput("not a date")).toBeNull();
      expect(parseJalaliInput("")).toBeNull();
    });
  });

  describe("ICU cross-check (Intl.DateTimeFormat, calendar: persian)", () => {
    function icuGregorianToJalali(g: { year: number; month: number; day: number }) {
      const formatter = new Intl.DateTimeFormat("en-US-u-ca-persian", {
        year: "numeric",
        month: "numeric",
        day: "numeric",
        timeZone: "UTC",
      });
      const parts = formatter.formatToParts(new Date(Date.UTC(g.year, g.month - 1, g.day)));
      const get = (type: string): number => Number(parts.find((p) => p.type === type)!.value);
      return { year: get("year"), month: get("month"), day: get("day") };
    }

    it.each([
      { year: 1990, month: 5, day: 15 },
      { year: 2024, month: 3, day: 20 },
      { year: 2025, month: 3, day: 20 },
      { year: 2025, month: 3, day: 21 },
      { year: 2025, month: 12, day: 22 },
      { year: 2026, month: 1, day: 10 },
      { year: 1979, month: 2, day: 11 },
    ])("jalaali-js agrees with the platform's ICU persian calendar for %o", (gregorian) => {
      expect(gregorianToJalali(gregorian)).toEqual(icuGregorianToJalali(gregorian));
    });
  });
});
